CREATE TABLE IF NOT EXISTS comments (
  id SERIAL PRIMARY KEY,
  name VARCHAR(20) NOT NULL DEFAULT 'Аноним',
  text TEXT NOT NULL,
  color VARCHAR(10) NOT NULL DEFAULT '#FFCC99',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
